// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var Helper;
    Helper = {
      version: 1.0,
      getQueryString: function(name, url) {
        var querystring, r, reg;
        reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)");
        querystring = arguments[1] != null ? arguments[1].substr(arguments[1].indexOf("?")) : window.location.search;
        r = querystring.substr(1).match(reg);
        if (r != null) {
          return unescape(r[2]);
        }
        return null;
      },
      getFileContent: function(fileInput, callback) {
        var file, reader;
        if (fileInput.files && fileInput.files.length > 0 && fileInput.files[0].size > 0) {
          file = fileInput.files[0];
          reader = new FileReader();
          reader.readAsText(file);
          return reader.onloadend = function(evt) {
            if (evt.target.readyState === FileReader.DONE) {
              return callback(evt.target.result);
            } else {
              return console.log("something went wrong!!");
            }
          };
        }
      }
    };
    return Helper;
  });

}).call(this);
