// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    baseUrl: "/prissearch/js/",
    paths: {
      'jquery': "./libs/jquery",
      'backbone': "./libs/backbone-min",
      'underscore': "./libs/underscore-min",
      'bootstrap': './../css/bootstrap/js/bootstrap.min',
      'Helper': './Helper',
      'simplePagination': './plugins/jquery.simplePagination'
    },
    shim: {
      'backbone': {
        deps: ["underscore", "jquery"],
        exports: "Backbone"
      },
      'underscore': {
        exports: "_"
      },
      'bootstrap': {
        deps: ['jquery'],
        exports: "jquery"
      },
      'simplePagination': {
        deps: ['jquery'],
        exports: "jquery"
      }
    }
  });

  require(['jquery', 'backbone', "Helper", 'bootstrap', 'simplePagination'], function($, Backbone, Helper) {
    return $(function() {
      var cIndex, fetchFromSina, itemsOnPage, updateInfo, updatePaginate, userNum, _ref, _ref1;
      updateInfo = function(index) {
        localStorage.setItem("currentIndex", index);
        $("#currentIndex").text(parseInt(index) + 1);
        $("#userid").text(localStorage.getItem("x" + index));
        return $("#bar_user_progress").width((parseInt(index) + 1) * 100 / (parseInt(localStorage.getItem('userNum'))) + "%");
      };
      updatePaginate = function(pageNum, itemsOnPage) {
        var i, userid, _i, _ref, _ref1, _results;
        $('#judge_result>tbody').html('');
        _results = [];
        for (i = _i = _ref = (pageNum - 1) * itemsOnPage, _ref1 = pageNum * itemsOnPage - 1; _ref <= _ref1 ? _i <= _ref1 : _i >= _ref1; i = _ref <= _ref1 ? ++_i : --_i) {
          userid = localStorage.getItem("x" + i);
          _results.push($("#judge_result>tbody").append("<tr>					<td>" + (i + 1) + "</td>					<td>" + userid + "</td>					<td>" + localStorage.getItem(userid) + "</td>					</tr>"));
        }
        return _results;
      };
      fetchFromSina = function(cIndex) {
        var uid;
        $("#weiboinfo").removeClass('bounceInLeft').addClass('animated bounceOutLeft');
        uid = localStorage.getItem("x" + cIndex);
        $("iframe").attr("src", "login_sina.php?userid=" + uid);
        return $("#weiboinfo").removeClass('bounceOutLeft').addClass('animated bounceInLeft');
      };
      userNum = (_ref = localStorage.getItem("userNum")) != null ? _ref : 0;
      cIndex = (_ref1 = localStorage.getItem("currentIndex")) != null ? _ref1 : 0;
      itemsOnPage = 5;
      $('#totalIndex').text(userNum);
      if (localStorage.getItem("x" + cIndex)) {
        updateInfo(cIndex);
        fetchFromSina(cIndex);
      }
      $(".btn_next_user").each(function(key, value) {
        return localStorage.setItem($(this).attr('alt'), key);
      });
      $("[rel=tooltip]").tooltip();
      $("#btn_loadfile").click(function(e) {
        e.preventDefault();
        console.log("start loading...");
        return Helper.getFileContent($('#userfile').get(0), function(result) {
          var i, idArr, userid, _i, _len;
          $('#no_next_user').hide();
          $('textarea').html(result);
          idArr = result.split("\r\n");
          userNum = idArr.length;
          for (i = _i = 0, _len = idArr.length; _i < _len; i = ++_i) {
            userid = idArr[i];
            localStorage.setItem("x" + i, userid);
          }
          localStorage.setItem("currentIndex", 0);
          localStorage.setItem("userNum", userNum);
          $('#totalIndex').text(userNum);
          cIndex = 0;
          updateInfo(0);
          return fetchFromSina(0);
        });
      });
      $("#btn_rmfile,#btn_chfile").click(function(e) {
        cIndex = 0;
        updateInfo(0);
        console.log("clear files.");
        $('#no_next_user').hide();
        localStorage.clear();
        $('textarea').html('');
        $("#currentIndex").text(0);
        $('#totalIndex').text(0);
        $("#bar_user_progress").width(0);
        return $("#weiboinfo").removeClass('bounceInLeft').addClass('animated bounceOutLeft');
      });
      $(".btn_next_user").click(function(e) {
        $('#no_pre_user').hide();
        localStorage.setItem(localStorage.getItem("x" + cIndex), $(this).attr('alt'));
        if (cIndex < parseInt(localStorage.getItem("userNum")) - 1) {
          console.log(">>>next user");
          cIndex = parseInt(cIndex) + 1;
          updateInfo(cIndex);
          return fetchFromSina(cIndex);
        } else {
          $('#no_next_user').removeClass('bounce');
          $('#no_next_user').show().addClass('animated bounce');
          return console.log("没有下一位用户了:" + cIndex);
        }
      });
      $("#btn_pre_user").click(function(e) {
        console.log(">>>previous user");
        $('#no_next_user').hide();
        if (cIndex > 0) {
          cIndex = parseInt(cIndex) - 1;
          updateInfo(cIndex);
          return fetchFromSina(cIndex);
        } else {
          $('#no_pre_user').removeClass('bounce');
          $('#no_pre_user').show().addClass('animated bounce');
          return console.log("现已是第一位用户了");
        }
      });
      $("#btn_show_result").click(function(e) {
        $('#myModal').modal("show");
        $("#mypagination").pagination({
          items: userNum,
          itemsOnPage: itemsOnPage,
          cssStyle: 'light-theme',
          prevText: '<<',
          nextText: '>>',
          onPageClick: function(pageNum, e) {
            return updatePaginate(pageNum, itemsOnPage);
          }
        });
        return updatePaginate(1, itemsOnPage);
      });
      $("#btn_save_result").click(function(e) {
        var i, spam_result, userid, _i, _ref2;
        spam_result = {};
        for (i = _i = 0, _ref2 = localStorage.getItem("userNum") - 1; 0 <= _ref2 ? _i <= _ref2 : _i >= _ref2; i = 0 <= _ref2 ? ++_i : --_i) {
          console.log(i);
          userid = localStorage.getItem("x" + i);
          spam_result[userid] = localStorage.getItem(userid);
        }
        return $.ajax({
          type: "POST",
          url: "save_result.php",
          dataType: "json",
          data: {
            result: JSON.stringify(spam_result)
          },
          success: function(data) {
            console.log(data);
            $(".spam_info").remove();
            if (data.isSaved) {
              $("<a class='spam_info' href='result.txt' target='_blank'>点击查看</a>").insertAfter("#btn_show_result");
            } else {
              $("<span class='spam_info label label-warning'>Sorry,no data</span>").insertAfter("#btn_show_result");
            }
            return $('#myModal').modal('hide');
          }
        });
      });
      return $(".btn").click(function(e) {
        return $(".spam_info").remove();
      });
    });
  });

}).call(this);
